#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#


ª
# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  20             \
    bottom_padding               20             \
    left_padding                 20             \
    right_padding                20             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap		\

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Calendar$" title="(General|^$)" manage=off
yabai -m rule --add label="System Settings" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" 
manage=off
yabai -m rule --add app="CleanShot X" manage=off mouse_follows_focus=off

# Startup config

for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 10
done


function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 browser
setup_space 2 code
setup_space 3 terminal
setup_space 4 mail
setup_space 5 music
setup_space 6 calendar
setup_space 7 things
setup_space 8 obsidian
setup_space 9 other

# move some apps automatically to specific spaces
# yabai -m rule --add app="^Chrome$" space=^1
# yabai -m rule --add app="^Code$" space=^2
# yabai -m rule --add app="^iTerm2$" space=^3
yabai -m rule --add app="^Mail$" space=^4
yabai -m rule --add app="^Spotify$" space=^5
yabai -m rule --add app="^Calendar$" space=^6
yabai -m rule --add app="^Things$" space=^7
yabai -m rule --add app="^Obsidian$" space=^8
yabai -m rule --add app="^Discord$" space=^9
yabai -m rule --add app="^Telegram$" space=^9
yabai -m rule --add app="^WhatsApp$" space=^9


echo "yabai configuration loaded.."
